apiVersion: v1
kind: Service
metadata:
  name: clusterbenchmark
  labels:
    app: protodemo
spec:
  ports:
  - port: 8080
    name: protoactor
  selector:
    app: protodemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterbenchmark-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: protodemo
  template:
    metadata:
      labels:
        app: protodemo
        version: v1
    spec:
      containers:
      - name: protodemo
        image: rogeralsing/clusterbenchmark
        imagePullPolicy: Always
        ports:
        - containerPort: 8080          